import turtle

viki = turtle.Turtle()
turtle.bgcolor("black")
viki.color("yellow")

def rect():
    viki.pensize(9)
    viki.forward(450)
    viki.left(45)
    viki.forward(6)
    viki.left(45)
    viki.forward(170)
    viki.left(45)
    viki.forward(6)
    viki.left(45)
    viki.forward(850)
    viki.left(45)
    viki.forward(6)
    viki.left(45)
    viki.forward(170)
    viki.left(45)
    viki.forward(6)
    viki.left(45)
    viki.forward(550)

def four_corner_lines():
    viki.pensize(12)
    viki.penup()
    viki.forward(320)
    viki.left(90)
    viki.forward(35)
    viki.left(90)
    viki.pendown()
    viki.forward(12)
    viki.penup()
    viki.forward(865)
    viki.pendown()
    viki.forward(17)
    viki.penup()
    viki.right(90)
    viki.forward(105)
    viki.right(90)
    viki.pendown()
    viki.forward(17)
    viki.penup()
    viki.forward(864)
    viki.pendown()
    viki.forward(12)

def i():
    viki.penup()
    viki.left(180)
    viki.forward(820)
    viki.pendown()
    viki.left(90)
    viki.forward(100)

def t():
    viki.penup()
    viki.right(90)
    viki.forward(-50)
    viki.right(270)
    viki.backward(100)
    viki.pendown()
    viki.forward(98)
    viki.left(90)
    viki.forward(25)
    viki.left(180)
    viki.forward(28)
    viki.right(90)
    viki.forward(60)
    viki.right(90)
    viki.forward(25)
    viki.right(180)
    viki.forward(50)

def s():
    viki.penup()
    viki.right(90)
    viki.forward(2)
    viki.right(270)
    viki.backward(105)
    viki.pendown()
    viki.forward(30)
    viki.left(90)
    viki.forward(30)
    viki.left(90)
    viki.forward(30)
    viki.right(90)
    viki.forward(30)
    viki.right(90)
    viki.forward(30)

def _():
    viki.penup()
    viki.right(90)
    viki.forward(2)
    viki.right(270)
    viki.backward(105)
    viki.pendown()
    viki.forward(40)

def v():
    viki.penup()
    viki.left(180)
    viki.forward(78)
    viki.pendown()
    viki.left(114)
    viki.forward(100)
    viki.left(180)
    viki.forward(100)
    viki.left(131)
    viki.forward(100)

def I():
    viki.penup()
    viki.left(295)
    viki.forward(23)
    viki.right(270)
    viki.backward(93)
    viki.pendown()
    viki.left(180)
    viki.backward(50)
    viki.penup()
    viki.right(180)
    viki.forward(30)
    viki.pendown()
    viki.left(180)
    viki.backward(3)

def k():
    viki.penup()
    viki.left(180)
    viki.forward(18)
    viki.right(270)
    viki.backward(32)
    viki.pendown()
    viki.left(90)
    viki.forward(100)
    viki.penup()
    viki.forward(-32)
    viki.left(47)
    viki.pendown()
    viki.forward(44)
    viki.left(180)
    viki.forward(44)
    viki.right(100)
    viki.forward(44)

def y():
    viki.penup()
    viki.right(39)
    viki.forward(23)
    viki.right(268)
    viki.backward(56)
    viki.pendown()
    viki.left(180)
    viki.backward(50)
    viki.penup()
    viki.right(180)
    viki.forward(30)
    viki.pendown()
    viki.left(180)
    viki.backward(3)

def gap():
    viki.penup()
    viki.left(180)
    viki.forward(-85)
    viki.right(270)
    viki.backward(68)
    viki.pendown()
    viki.forward(40)

def d():
    viki.penup()
    viki.left(180)
    viki.forward(115)
    viki.right(270)
    viki.backward(1)
    viki.pendown()
    viki.forward(100)
    viki.left(180)
    viki.forward(100)
    viki.right(90)
    viki.forward(40)
    viki.right(90)
    viki.forward(48)
    viki.right(90)
    viki.forward(40)

def V():
    viki.penup()
    viki.forward(24)
    viki.left(115)
    viki.backward(50)
    viki.pendown()
    viki.forward(50)
    viki.left(180)
    viki.forward(50)
    viki.left(131)
    viki.forward(50)

def gap1():
    viki.penup()
    viki.forward(-50)
    viki.right(68)
    viki.backward(-28)
    viki.pendown()
    viki.forward(40)

def I1():
    viki.penup()
    viki.backward(-30)
    viki.left(91)
    viki.forward(3)
    viki.pendown()
    viki.left(180)
    viki.backward(65)
    viki.penup()
    viki.right(180)
    viki.forward(30)
    viki.pendown()
    viki.left(180)
    viki.backward(3)

def S():
    viki.penup()
    viki.backward(-35)
    viki.right(90)
    viki.forward(-52)
    viki.pendown()
    viki.forward(30)
    viki.left(90)
    viki.forward(30)
    viki.left(90)
    viki.forward(30)
    viki.right(90)
    viki.forward(30)
    viki.right(90)
    viki.forward(30)


rect()
four_corner_lines()
i()
t()
s()
_()
v()
I()
k()
y()
gap()
d()
V()
gap1()
I1()
S()

turtle.done()

